### PR TITLE
STK492 - Updates the Display Adress to remove asterisk in the PLP

### PR DESCRIPTION
**Pull request by franciellyferreira**
It was necessary to change the sender address in PLP to use the number with the asterisk removal filter.

### CODE REVIEW

**Review by lucaspolo — APPROVED** [review]

**Review by lucaspolo — CHANGES_REQUESTED** [review]
Maybe you can make some unit test for the changing.

**Comment by franciellyferreira** [comment]
> Maybe you can make some unit test for the changing.

**Comment by franciellyferreira** [comment]
> Maybe you can make some unit test for the changing.

Ok!

**Comment by franciellyferreira** [comment]
@lucaspolo Test created

**Review by lucaspolo — APPROVED** [review]

**Review by talitavaleria — APPROVED** [review]

**Pull request merged**
